services:
  qBittorrent-sorter:
    build: .
    environment:
      TZ: "Europe/Moscow"
      QBITTORRENT_HOST: "http://192.168.0.100"
      QBITTORRENT_PORT: 9001
      MOVIES_PATH: "/downloads/movies"
      SHOWS_PATH: "/downloads/shows"
      MISC_PATH: "/downloads/data"
      QBITTORRENT_USERNAME: "admin"
      QBITTORRENT_PASSWORD: "admin"
      REFRESH_INTERVAL: "60"
      RETRY_INTERVAL: "60"
      LOG_LEVEL: "INFO"
